name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check for Cloudflare Worker Token
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_WORKER_TOKEN }}" ]; then
            echo "CLOUDFLARE_WORKER_TOKEN is not set."
            exit 1
          else
            echo "CLOUDFLARE_WORKER_TOKEN is set."
          fi

      - name: Deploy to Cloudflare
        if: success() # Only run if the previous step succeeded
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKER_TOKEN }}
        run: bun run deploy
